<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Flora Hamilton">
<meta name="dcterms.date" content="2022-12-15">
<meta name="description" content="Evaluating data from the Harvard Forest LTER soil warming experiment to simulate global climate change">

<title>Does global warming affect soil respiration?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">floraham.github.io</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../CV.html" rel="" target="">
 <span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Projects.html" rel="" target="">
 <span class="menu-text">Projects</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#background" id="toc-background" class="nav-link active" data-scroll-target="#background">Background:</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The Data</a></li>
  <li><a href="#cleaning-preparing-for-analysis" id="toc-cleaning-preparing-for-analysis" class="nav-link" data-scroll-target="#cleaning-preparing-for-analysis">Cleaning + preparing for analysis 🧼</a>
  <ul class="collapse">
  <li><a href="#exploratory-data-visualizations" id="toc-exploratory-data-visualizations" class="nav-link" data-scroll-target="#exploratory-data-visualizations">Exploratory Data Visualizations 👀</a>
  <ul class="collapse">
  <li><a href="#averaging-by-month-or-year" id="toc-averaging-by-month-or-year" class="nav-link" data-scroll-target="#averaging-by-month-or-year">Averaging by month or year?</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">Analysis</a>
  <ul class="collapse">
  <li><a href="#evaluating-significant-differences-in-average-co2-flux-between-treatment-and-control-plots" id="toc-evaluating-significant-differences-in-average-co2-flux-between-treatment-and-control-plots" class="nav-link" data-scroll-target="#evaluating-significant-differences-in-average-co2-flux-between-treatment-and-control-plots">Evaluating significant differences in average CO2 flux between treatment and control plots</a></li>
  </ul></li>
  <li><a href="#defining-a-regression-model" id="toc-defining-a-regression-model" class="nav-link" data-scroll-target="#defining-a-regression-model">Defining a regression model</a>
  <ul class="collapse">
  <li><a href="#model-0-single-variable-categorical-regression" id="toc-model-0-single-variable-categorical-regression" class="nav-link" data-scroll-target="#model-0-single-variable-categorical-regression">Model 0) Single variable, categorical regression</a></li>
  <li><a href="#model-1-multiple-regression" id="toc-model-1-multiple-regression" class="nav-link" data-scroll-target="#model-1-multiple-regression">Model 1) multiple regression</a></li>
  <li><a href="#addressing-ommited-variables-bias" id="toc-addressing-ommited-variables-bias" class="nav-link" data-scroll-target="#addressing-ommited-variables-bias">Addressing ommited variables bias</a></li>
  <li><a href="#model-2-multiple-regression-with-interaction-term" id="toc-model-2-multiple-regression-with-interaction-term" class="nav-link" data-scroll-target="#model-2-multiple-regression-with-interaction-term">Model 2) multiple regression with interaction term</a></li>
  <li><a href="#limitations-next-steps" id="toc-limitations-next-steps" class="nav-link" data-scroll-target="#limitations-next-steps">Limitations + next steps</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Does global warming affect soil respiration?</h1>
</div>

<div>
  <div class="description">
    Evaluating data from the Harvard Forest LTER soil warming experiment to simulate global climate change
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Flora Hamilton </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 15, 2022</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="images/Screenshot 2023-12-15 at 9.26.16 AM.png" class="img-fluid"></p>
<p><em>What effect does soil warming have on monthly average respiration rates?</em></p>
<section id="background" class="level1">
<h1>Background:</h1>
<p>The Intergovernmental Panel on Climate Change (IPCC)’s AR6 report published in August, 2021 projects that the world will likely reach or exceed 1.5 degrees C (2.7 degrees F) of warming within the next two decades <a href="https://www.wri.org/insights/ipcc-climate-report">[1]</a>. Under these circumstances, preserving soil health will be evermore important. Soil respiration, or “carbon flux,” plays a significant role in soil health and the global carbon and nutrient cycles, and can be considered the “vitality” of the soil, as it is an indicator of microbial activity and the content and decomposition of soil organic matter. Carbon flux is measured as the rate of carbon dioxide released from the soil by microbes decomposing soil organic matter and from the respiration of plant roots, in units of micromoles of CO2 per meter squared, per second.</p>
<p>The Harvard Forest LTER (Long Term Ecological Research) station has been “examining ecological dynamics in the New England region resulting from natural disturbances, environmental change, and human impacts” since the early 1990’s <a href="https://portal.edirepository.org/nis/metadataviewer?packageid=knb-lter-hfr.18.34">[2]</a>. One of their main focuses is studying the effects of soil warming on soil respiration, nutrient availbility, carbon sequestration, and other ecoystemic factors impacted by global warming.</p>
<p>One of its most important research findings is that soil respiration is also a driver for, and thus associated with, positive feedback with global climate change [<a href="https://harvardforest.fas.harvard.edu/news/results-20-year-soil-warming-experiment">3</a>]. To arrive at this conclusion, the researchers designated control and temperature-treated plots of soil, maintaining soil temperatures at 5°C above ambient levels via hot wires running underneath the soil surface, at three replicated sites <a href="https://harvardforest.fas.harvard.edu/soil-warming-experiment">[4]</a>.</p>
<p>While these research findings have been formalized by the studies’ scientists, I would like to better understand the relationship between soil warming and soil respiration for myself by applying hypothesis testing and linear regression, using the data from the Barre Woods site to evaluate changes of carbon flux based on differences in soil temperature and soil moisture.</p>
</section>
<section id="the-data" class="level1">
<h1>The Data</h1>
<p>The data used in this project was retrieved from <a href="https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-hfr&amp;identifier=18&amp;revision=34">this EDI Portal</a>, with a temporal range of 2001 to 2019</p>
<p>🌡️ <strong>Soil temperature data</strong> (<a href="https://dex.edirepository.org/https%3A%2F%2Fpasta.lternet.edu%2Fpackage%2Fdata%2Feml%2Fknb-lter-hfr%2F18%2F34%2F326d32c64ccd7337a0f88b91db895e55">Explore data here and sampling methods here</a>)</p>
<p>The EDI Portal provides R code to assist with the data wrangling. This is the code chunk I used for reading in the file &amp; performing preliminary cleaning.</p>
<div class="cell" data-warnings="false">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(feasts)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(moderndive)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># reading in temperature data </span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>infile3 <span class="ot">&lt;-</span> <span class="fu">trimws</span>(<span class="st">"https://pasta.lternet.edu/package/data/eml/knb-lter-hfr/18/34/9967b5716716078674fdd9755f9d5f1f"</span>) </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>infile3 <span class="ot">&lt;-</span><span class="fu">sub</span>(<span class="st">"^https"</span>,<span class="st">"http"</span>,infile3)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># This creates a tibble named: dt3 </span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    dt3 <span class="ot">&lt;-</span><span class="fu">read_delim</span>(infile3  </span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>                ,<span class="at">delim=</span><span class="st">","</span>   </span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>                ,<span class="at">skip=</span><span class="dv">1</span> </span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>                    , <span class="at">col_names=</span><span class="fu">c</span>( </span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"datetime"</span>,   </span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"doy"</span>,   </span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"year"</span>,   </span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"time"</span>,   </span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"ctrl.av"</span>,   </span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"p1.av"</span>,   </span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"p2.av"</span>,   </span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"p3.av"</span>,   </span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"p4.av"</span>,   </span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"p5.av"</span>,   </span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"p6.av"</span>,   </span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"p7.av"</span>,   </span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"p8.av"</span>,   </span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"p9.av"</span>,   </span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"p10.av"</span>   ), </span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>                    <span class="at">col_types=</span><span class="fu">list</span>( </span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">col_datetime</span>(<span class="st">"%Y-%m-%dT%H:%M"</span>), </span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>                                    </span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">col_number</span>() , </span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">col_character</span>(),  </span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">col_character</span>(), </span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">col_number</span>() , </span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">col_number</span>() , </span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">col_number</span>() , </span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">col_number</span>() , </span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">col_number</span>() , </span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">col_number</span>() , </span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">col_number</span>() , </span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">col_number</span>() , </span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">col_number</span>() , </span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">col_number</span>() , </span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">col_number</span>() ), </span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>                        <span class="at">na=</span><span class="fu">c</span>(<span class="st">" "</span>,<span class="st">"."</span>,<span class="st">"NA"</span>,<span class="st">""</span>)  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat &lt;- vroom(...)
  problems(dat)</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert Missing Values to NA for individual vectors </span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>dt3<span class="sc">$</span>datetime <span class="ot">&lt;-</span> <span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>datetime))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,dt3<span class="sc">$</span>datetime)               </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(dt3<span class="sc">$</span>datetime <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>)) <span class="sc">&amp;</span> (<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>datetime))<span class="sc">==</span><span class="fu">as.character</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>))),<span class="cn">NA</span>,dt3<span class="sc">$</span>datetime))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>dt3<span class="sc">$</span>doy <span class="ot">&lt;-</span> <span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>doy))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,dt3<span class="sc">$</span>doy)               </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(dt3<span class="sc">$</span>doy <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>)) <span class="sc">&amp;</span> (<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>doy))<span class="sc">==</span><span class="fu">as.character</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>))),<span class="cn">NA</span>,dt3<span class="sc">$</span>doy))</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>dt3<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>year))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,dt3<span class="sc">$</span>year)               </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(dt3<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>)) <span class="sc">&amp;</span> (<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>year))<span class="sc">==</span><span class="fu">as.character</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>))),<span class="cn">NA</span>,dt3<span class="sc">$</span>year))</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>dt3<span class="sc">$</span>time <span class="ot">&lt;-</span> <span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>time))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,dt3<span class="sc">$</span>time)               </span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(dt3<span class="sc">$</span>time <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>)) <span class="sc">&amp;</span> (<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>time))<span class="sc">==</span><span class="fu">as.character</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>))),<span class="cn">NA</span>,dt3<span class="sc">$</span>time))</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>dt3<span class="sc">$</span>ctrl.av <span class="ot">&lt;-</span> <span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>ctrl.av))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,dt3<span class="sc">$</span>ctrl.av)               </span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(dt3<span class="sc">$</span>ctrl.av <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>)) <span class="sc">&amp;</span> (<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>ctrl.av))<span class="sc">==</span><span class="fu">as.character</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>))),<span class="cn">NA</span>,dt3<span class="sc">$</span>ctrl.av))</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>dt3<span class="sc">$</span>p1.av <span class="ot">&lt;-</span> <span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>p1.av))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,dt3<span class="sc">$</span>p1.av)               </span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(dt3<span class="sc">$</span>p1.av <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>)) <span class="sc">&amp;</span> (<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>p1.av))<span class="sc">==</span><span class="fu">as.character</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>))),<span class="cn">NA</span>,dt3<span class="sc">$</span>p1.av))</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>dt3<span class="sc">$</span>p2.av <span class="ot">&lt;-</span> <span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>p2.av))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,dt3<span class="sc">$</span>p2.av)               </span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(dt3<span class="sc">$</span>p2.av <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>)) <span class="sc">&amp;</span> (<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>p2.av))<span class="sc">==</span><span class="fu">as.character</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>))),<span class="cn">NA</span>,dt3<span class="sc">$</span>p2.av))</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>dt3<span class="sc">$</span>p3.av <span class="ot">&lt;-</span> <span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>p3.av))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,dt3<span class="sc">$</span>p3.av)               </span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(dt3<span class="sc">$</span>p3.av <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>)) <span class="sc">&amp;</span> (<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>p3.av))<span class="sc">==</span><span class="fu">as.character</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>))),<span class="cn">NA</span>,dt3<span class="sc">$</span>p3.av))</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>dt3<span class="sc">$</span>p4.av <span class="ot">&lt;-</span> <span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>p4.av))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,dt3<span class="sc">$</span>p4.av)               </span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(dt3<span class="sc">$</span>p4.av <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>)) <span class="sc">&amp;</span> (<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>p4.av))<span class="sc">==</span><span class="fu">as.character</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>))),<span class="cn">NA</span>,dt3<span class="sc">$</span>p4.av))</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>dt3<span class="sc">$</span>p5.av <span class="ot">&lt;-</span> <span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>p5.av))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,dt3<span class="sc">$</span>p5.av)               </span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(dt3<span class="sc">$</span>p5.av <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>)) <span class="sc">&amp;</span> (<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>p5.av))<span class="sc">==</span><span class="fu">as.character</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>))),<span class="cn">NA</span>,dt3<span class="sc">$</span>p5.av))</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>dt3<span class="sc">$</span>p6.av <span class="ot">&lt;-</span> <span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>p6.av))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,dt3<span class="sc">$</span>p6.av)               </span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(dt3<span class="sc">$</span>p6.av <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>)) <span class="sc">&amp;</span> (<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>p6.av))<span class="sc">==</span><span class="fu">as.character</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>))),<span class="cn">NA</span>,dt3<span class="sc">$</span>p6.av))</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>dt3<span class="sc">$</span>p7.av <span class="ot">&lt;-</span> <span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>p7.av))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,dt3<span class="sc">$</span>p7.av)               </span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(dt3<span class="sc">$</span>p7.av <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>)) <span class="sc">&amp;</span> (<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>p7.av))<span class="sc">==</span><span class="fu">as.character</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>))),<span class="cn">NA</span>,dt3<span class="sc">$</span>p7.av))</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>dt3<span class="sc">$</span>p8.av <span class="ot">&lt;-</span> <span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>p8.av))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,dt3<span class="sc">$</span>p8.av)               </span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(dt3<span class="sc">$</span>p8.av <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>)) <span class="sc">&amp;</span> (<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>p8.av))<span class="sc">==</span><span class="fu">as.character</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>))),<span class="cn">NA</span>,dt3<span class="sc">$</span>p8.av))</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>dt3<span class="sc">$</span>p9.av <span class="ot">&lt;-</span> <span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>p9.av))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,dt3<span class="sc">$</span>p9.av)               </span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(dt3<span class="sc">$</span>p9.av <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>)) <span class="sc">&amp;</span> (<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>p9.av))<span class="sc">==</span><span class="fu">as.character</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>))),<span class="cn">NA</span>,dt3<span class="sc">$</span>p9.av))</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>dt3<span class="sc">$</span>p10.av <span class="ot">&lt;-</span> <span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>p10.av))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,dt3<span class="sc">$</span>p10.av)               </span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(dt3<span class="sc">$</span>p10.av <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>)) <span class="sc">&amp;</span> (<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt3<span class="sc">$</span>p10.av))<span class="sc">==</span><span class="fu">as.character</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>))),<span class="cn">NA</span>,dt3<span class="sc">$</span>p10.av))</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>                  </span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>soiltemp_df <span class="ot">&lt;-</span> dt3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><strong>💧 💨 Soil respiration + moisture data</strong> (<a href="https://dex.edirepository.org/https%3A%2F%2Fpasta.lternet.edu%2Fpackage%2Fdata%2Feml%2Fknb-lter-hfr%2F18%2F34%2F6f307eb9dfd8291d8826d69d73c18d27">Explore data and sampling methods here</a>):</p>
<p>Reading in file &amp; cleaning.</p>
<div class="cell" data-warnings="false">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>inUrl7  <span class="ot">&lt;-</span> <span class="st">"https://pasta.lternet.edu/package/data/eml/knb-lter-hfr/18/33/6f307eb9dfd8291d8826d69d73c18d27"</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>infile7 <span class="ot">&lt;-</span> <span class="fu">tempfile</span>()</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">try</span>(<span class="fu">download.file</span>(inUrl7,infile7,<span class="at">method=</span><span class="st">"curl"</span>))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">is.na</span>(<span class="fu">file.size</span>(infile7))) <span class="fu">download.file</span>(inUrl7,infile7,<span class="at">method=</span><span class="st">"auto"</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>dt7 <span class="ot">&lt;-</span><span class="fu">read.csv</span>(infile7,<span class="at">header=</span>F </span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>          ,<span class="at">skip=</span><span class="dv">1</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>            ,<span class="at">sep=</span><span class="st">","</span>  </span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>        , <span class="at">col.names=</span><span class="fu">c</span>(</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"datetime"</span>,     </span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"date"</span>,     </span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"year"</span>,     </span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"month"</span>,     </span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"day"</span>,     </span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"time"</span>,     </span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"treatment"</span>,     </span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"plot"</span>,     </span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"co2"</span>,     </span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"cm2"</span>,     </span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"cm4"</span>,     </span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"moisture"</span>,     </span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"measurement"</span>    ), <span class="at">check.names=</span><span class="cn">TRUE</span>)</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>               </span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a><span class="fu">unlink</span>(infile7)</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>            </span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Fix any interval or ratio columns mistakenly read in as nominal and nominal columns read as numeric or dates read as strings</span></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>                </span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt7<span class="sc">$</span>datetime)<span class="sc">!=</span><span class="st">"factor"</span>) dt7<span class="sc">$</span>datetime<span class="ot">&lt;-</span> <span class="fu">as.factor</span>(dt7<span class="sc">$</span>datetime)                                   </span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a><span class="co"># attempting to convert dt7$date dateTime string to R date structure (date or POSIXct)                                </span></span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>tmpDateFormat<span class="ot">&lt;-</span><span class="st">"%Y-%m-%d"</span></span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>tmp7date<span class="ot">&lt;-</span><span class="fu">as.Date</span>(dt7<span class="sc">$</span>date,<span class="at">format=</span>tmpDateFormat)</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep the new dates only if they all converted correctly</span></span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="fu">length</span>(tmp7date) <span class="sc">==</span> <span class="fu">length</span>(tmp7date[<span class="sc">!</span><span class="fu">is.na</span>(tmp7date)])){dt7<span class="sc">$</span>date <span class="ot">&lt;-</span> tmp7date } <span class="cf">else</span> {<span class="fu">print</span>(<span class="st">"Date conversion failed for dt7$date. Please inspect the data and do the date conversion yourself."</span>)}                                                                    </span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(tmpDateFormat,tmp7date) </span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt7<span class="sc">$</span>month)<span class="sc">!=</span><span class="st">"factor"</span>) dt7<span class="sc">$</span>month<span class="ot">&lt;-</span> <span class="fu">as.factor</span>(dt7<span class="sc">$</span>month)</span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt7<span class="sc">$</span>day)<span class="sc">!=</span><span class="st">"factor"</span>) dt7<span class="sc">$</span>day<span class="ot">&lt;-</span> <span class="fu">as.factor</span>(dt7<span class="sc">$</span>day)</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt7<span class="sc">$</span>treatment)<span class="sc">!=</span><span class="st">"factor"</span>) dt7<span class="sc">$</span>treatment<span class="ot">&lt;-</span> <span class="fu">as.factor</span>(dt7<span class="sc">$</span>treatment)</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt7<span class="sc">$</span>plot)<span class="sc">!=</span><span class="st">"factor"</span>) dt7<span class="sc">$</span>plot<span class="ot">&lt;-</span> <span class="fu">as.factor</span>(dt7<span class="sc">$</span>plot)</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt7<span class="sc">$</span>co2)<span class="sc">==</span><span class="st">"factor"</span>) dt7<span class="sc">$</span>co2 <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(<span class="fu">levels</span>(dt7<span class="sc">$</span>co2))[<span class="fu">as.integer</span>(dt7<span class="sc">$</span>co2) ]               </span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt7<span class="sc">$</span>co2)<span class="sc">==</span><span class="st">"character"</span>) dt7<span class="sc">$</span>co2 <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(dt7<span class="sc">$</span>co2)</span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt7<span class="sc">$</span>cm2)<span class="sc">==</span><span class="st">"factor"</span>) dt7<span class="sc">$</span>cm2 <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(<span class="fu">levels</span>(dt7<span class="sc">$</span>cm2))[<span class="fu">as.integer</span>(dt7<span class="sc">$</span>cm2) ]               </span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt7<span class="sc">$</span>cm2)<span class="sc">==</span><span class="st">"character"</span>) dt7<span class="sc">$</span>cm2 <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(dt7<span class="sc">$</span>cm2)</span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt7<span class="sc">$</span>cm4)<span class="sc">==</span><span class="st">"factor"</span>) dt7<span class="sc">$</span>cm4 <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(<span class="fu">levels</span>(dt7<span class="sc">$</span>cm4))[<span class="fu">as.integer</span>(dt7<span class="sc">$</span>cm4) ]               </span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt7<span class="sc">$</span>cm4)<span class="sc">==</span><span class="st">"character"</span>) dt7<span class="sc">$</span>cm4 <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(dt7<span class="sc">$</span>cm4)</span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt7<span class="sc">$</span>moisture)<span class="sc">==</span><span class="st">"factor"</span>) dt7<span class="sc">$</span>moisture <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(<span class="fu">levels</span>(dt7<span class="sc">$</span>moisture))[<span class="fu">as.integer</span>(dt7<span class="sc">$</span>moisture) ]               </span>
<span id="cb4-48"><a href="#cb4-48" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt7<span class="sc">$</span>moisture)<span class="sc">==</span><span class="st">"character"</span>) dt7<span class="sc">$</span>moisture <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(dt7<span class="sc">$</span>moisture)</span>
<span id="cb4-49"><a href="#cb4-49" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">class</span>(dt7<span class="sc">$</span>measurement)<span class="sc">!=</span><span class="st">"factor"</span>) dt7<span class="sc">$</span>measurement<span class="ot">&lt;-</span> <span class="fu">as.factor</span>(dt7<span class="sc">$</span>measurement)</span>
<span id="cb4-50"><a href="#cb4-50" aria-hidden="true" tabindex="-1"></a>                </span>
<span id="cb4-51"><a href="#cb4-51" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert Missing Values to NA for non-dates</span></span>
<span id="cb4-52"><a href="#cb4-52" aria-hidden="true" tabindex="-1"></a>                </span>
<span id="cb4-53"><a href="#cb4-53" aria-hidden="true" tabindex="-1"></a>dt7<span class="sc">$</span>datetime <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt7<span class="sc">$</span>datetime))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,<span class="fu">as.character</span>(dt7<span class="sc">$</span>datetime)))</span>
<span id="cb4-54"><a href="#cb4-54" aria-hidden="true" tabindex="-1"></a>dt7<span class="sc">$</span>month <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt7<span class="sc">$</span>month))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,<span class="fu">as.character</span>(dt7<span class="sc">$</span>month)))</span>
<span id="cb4-55"><a href="#cb4-55" aria-hidden="true" tabindex="-1"></a>dt7<span class="sc">$</span>day <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt7<span class="sc">$</span>day))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,<span class="fu">as.character</span>(dt7<span class="sc">$</span>day)))</span>
<span id="cb4-56"><a href="#cb4-56" aria-hidden="true" tabindex="-1"></a>dt7<span class="sc">$</span>treatment <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt7<span class="sc">$</span>treatment))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,<span class="fu">as.character</span>(dt7<span class="sc">$</span>treatment)))</span>
<span id="cb4-57"><a href="#cb4-57" aria-hidden="true" tabindex="-1"></a>dt7<span class="sc">$</span>plot <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt7<span class="sc">$</span>plot))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,<span class="fu">as.character</span>(dt7<span class="sc">$</span>plot)))</span>
<span id="cb4-58"><a href="#cb4-58" aria-hidden="true" tabindex="-1"></a>dt7<span class="sc">$</span>co2 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt7<span class="sc">$</span>co2))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,dt7<span class="sc">$</span>co2)               </span>
<span id="cb4-59"><a href="#cb4-59" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(dt7<span class="sc">$</span>co2 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>)) <span class="sc">&amp;</span> (<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt7<span class="sc">$</span>co2))<span class="sc">==</span><span class="fu">as.character</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>))),<span class="cn">NA</span>,dt7<span class="sc">$</span>co2))</span>
<span id="cb4-60"><a href="#cb4-60" aria-hidden="true" tabindex="-1"></a>dt7<span class="sc">$</span>cm2 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt7<span class="sc">$</span>cm2))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,dt7<span class="sc">$</span>cm2)               </span>
<span id="cb4-61"><a href="#cb4-61" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(dt7<span class="sc">$</span>cm2 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>)) <span class="sc">&amp;</span> (<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt7<span class="sc">$</span>cm2))<span class="sc">==</span><span class="fu">as.character</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>))),<span class="cn">NA</span>,dt7<span class="sc">$</span>cm2))</span>
<span id="cb4-62"><a href="#cb4-62" aria-hidden="true" tabindex="-1"></a>dt7<span class="sc">$</span>cm4 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt7<span class="sc">$</span>cm4))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,dt7<span class="sc">$</span>cm4)               </span>
<span id="cb4-63"><a href="#cb4-63" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(dt7<span class="sc">$</span>cm4 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>)) <span class="sc">&amp;</span> (<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt7<span class="sc">$</span>cm4))<span class="sc">==</span><span class="fu">as.character</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>))),<span class="cn">NA</span>,dt7<span class="sc">$</span>cm4))</span>
<span id="cb4-64"><a href="#cb4-64" aria-hidden="true" tabindex="-1"></a>dt7<span class="sc">$</span>moisture <span class="ot">&lt;-</span> <span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt7<span class="sc">$</span>moisture))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,dt7<span class="sc">$</span>moisture)               </span>
<span id="cb4-65"><a href="#cb4-65" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(dt7<span class="sc">$</span>moisture <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>)) <span class="sc">&amp;</span> (<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt7<span class="sc">$</span>moisture))<span class="sc">==</span><span class="fu">as.character</span>(<span class="fu">as.numeric</span>(<span class="st">"NA"</span>))),<span class="cn">NA</span>,dt7<span class="sc">$</span>moisture))</span>
<span id="cb4-66"><a href="#cb4-66" aria-hidden="true" tabindex="-1"></a>dt7<span class="sc">$</span>measurement <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">ifelse</span>((<span class="fu">trimws</span>(<span class="fu">as.character</span>(dt7<span class="sc">$</span>measurement))<span class="sc">==</span><span class="fu">trimws</span>(<span class="st">"NA"</span>)),<span class="cn">NA</span>,<span class="fu">as.character</span>(dt7<span class="sc">$</span>measurement)))</span>
<span id="cb4-67"><a href="#cb4-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-68"><a href="#cb4-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-69"><a href="#cb4-69" aria-hidden="true" tabindex="-1"></a><span class="co"># Here is the structure of the input data frame:</span></span>
<span id="cb4-70"><a href="#cb4-70" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dt7)                            </span>
<span id="cb4-71"><a href="#cb4-71" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(dt7)                            </span>
<span id="cb4-72"><a href="#cb4-72" aria-hidden="true" tabindex="-1"></a><span class="co"># The analyses below are basic descriptions of the variables. After testing, they should be replaced.                 </span></span>
<span id="cb4-73"><a href="#cb4-73" aria-hidden="true" tabindex="-1"></a>                <span class="co"># Get more details on character variables</span></span>
<span id="cb4-74"><a href="#cb4-74" aria-hidden="true" tabindex="-1"></a>                 </span>
<span id="cb4-75"><a href="#cb4-75" aria-hidden="true" tabindex="-1"></a><span class="fu">detach</span>(dt7)   </span>
<span id="cb4-76"><a href="#cb4-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-77"><a href="#cb4-77" aria-hidden="true" tabindex="-1"></a>co2flux_df <span class="ot">&lt;-</span> dt7</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="cleaning-preparing-for-analysis" class="level1">
<h1>Cleaning + preparing for analysis 🧼</h1>
<p>Aligning data with the some datetime specifications</p>
<div class="cell" data-warnings="false">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-------------------co2 data cleaning--------------------#</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Convert the date time using lubridate with co2 data </span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>co2flux_df<span class="sc">$</span>datetime <span class="ot">=</span> <span class="fu">as_datetime</span>(co2flux_df<span class="sc">$</span>datetime)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a datetime column using lubridate</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>co2flux_df<span class="sc">$</span>datetime <span class="ot">&lt;-</span> <span class="fu">ymd</span>(<span class="fu">paste</span>(co2flux_df<span class="sc">$</span>year, co2flux_df<span class="sc">$</span>month, co2flux_df<span class="sc">$</span>day, <span class="at">sep =</span> <span class="st">"-"</span>)) <span class="sc">+</span> <span class="fu">hm</span>(co2flux_df<span class="sc">$</span>time)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>co2flux_df<span class="sc">$</span>date <span class="ot">&lt;-</span>  <span class="fu">date</span>(co2flux_df<span class="sc">$</span>datetime)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co">#------------------soil temp data cleaning--------------#</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co">#Convert the date time using lubridate with temperature data </span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>soiltemp_df<span class="sc">$</span>datetime <span class="ot">&lt;-</span> <span class="fu">as_datetime</span>(soiltemp_df<span class="sc">$</span>datetime)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract day, month, and year</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>day <span class="ot">&lt;-</span> <span class="fu">sprintf</span>(<span class="st">"%02d"</span>, <span class="fu">day</span>(soiltemp_df<span class="sc">$</span>datetime))</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>month <span class="ot">&lt;-</span> <span class="fu">sprintf</span>(<span class="st">"%02d"</span>, <span class="fu">month</span>(soiltemp_df<span class="sc">$</span>datetime))</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>year <span class="ot">&lt;-</span> <span class="fu">year</span>(soiltemp_df<span class="sc">$</span>datetime)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>soiltemp_df<span class="sc">$</span>date <span class="ot">&lt;-</span> <span class="fu">paste</span>(year, month, day, <span class="at">sep =</span> <span class="st">'-'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Because the soiltemp records temperature at individual plots, we also want to average all the plots by date and across all plots</p>
<div class="cell" data-warnings="false">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify columns to average across</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>columns_to_average <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"p1.av"</span>, <span class="st">"p2.av"</span>, <span class="st">"p3.av"</span>, <span class="st">"p4.av"</span>, <span class="st">"p5.av"</span>, <span class="st">"p6.av"</span>, <span class="st">"p7.av"</span>, <span class="st">"p8.av"</span>, <span class="st">"p9.av"</span>, <span class="st">"p10.av"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the row-wise mean for the selected columns</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>soiltemp_df <span class="ot">&lt;-</span> soiltemp_df <span class="sc">%&gt;%</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">treatment.avgT =</span> <span class="fu">mean</span>(<span class="fu">c_across</span>(<span class="fu">all_of</span>(columns_to_average)), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">ctrl.avgT=</span>ctrl.av) <span class="sc">%&gt;%</span> </span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>p1.av, <span class="sc">-</span>p2.av, <span class="sc">-</span>p3.av, <span class="sc">-</span>p4.av, <span class="sc">-</span>p5.av, <span class="sc">-</span>p6.av, <span class="sc">-</span>p7.av, <span class="sc">-</span>p8.av, <span class="sc">-</span>p9.av, <span class="sc">-</span>p10.av, <span class="sc">-</span>doy, <span class="sc">-</span>year, <span class="sc">-</span>time) <span class="sc">%&gt;%</span>  <span class="co">#drop columns </span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(date, ctrl.avgT, treatment.avgT) <span class="co">#reorder columns</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Group by and average both data frames by to get a daily average.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#co2flux_df </span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co">#soiltemp_df</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co">#group by date and average </span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>soiltemp_df_avgs <span class="ot">&lt;-</span> soiltemp_df <span class="sc">%&gt;%</span> </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(date) <span class="sc">%&gt;%</span> </span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">treatment.avgT_daily =</span> <span class="fu">mean</span>(treatment.avgT), <span class="at">ctrl.avgT_daily=</span> <span class="fu">mean</span>(ctrl.avgT))</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>co2flux <span class="ot">&lt;-</span> co2flux_df <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="st">"datetime"</span>, <span class="st">"treatment"</span>, <span class="st">"co2"</span>, <span class="st">"moisture"</span>, <span class="st">"date"</span>) <span class="sc">%&gt;%</span> <span class="fu">filter</span>(treatment <span class="sc">==</span> <span class="st">"H"</span> <span class="sc">|</span> treatment <span class="sc">==</span> <span class="st">"C"</span>) </span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>co2flux_avgs <span class="ot">&lt;-</span> co2flux <span class="sc">%&gt;%</span>  <span class="fu">group_by</span>(date, treatment) <span class="sc">%&gt;%</span> </span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avg_co2 =</span> <span class="fu">mean</span>(co2), <span class="at">avg_moisture =</span> <span class="fu">mean</span>(moisture)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'date'. You can override using the
`.groups` argument.</code></pre>
</div>
</div>
<section id="exploratory-data-visualizations" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-visualizations">Exploratory Data Visualizations 👀</h2>
<p>I plot the raw carbon flux data over time to gain a better understanding of the underlying dataset, hoping to visually identify trends and notice patterns upon first assessment.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>raw <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>co2flux, <span class="fu">aes</span>(<span class="at">x=</span>date, <span class="at">y=</span>co2, <span class="at">color =</span> treatment)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>)  <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"Date"</span>) <span class="sc">+</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">"CO2 flux, μmol/(m²·s) "</span>)  <span class="sc">+</span> </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_date</span>(<span class="at">date_breaks =</span> <span class="st">"1 year"</span>, <span class="at">date_labels =</span> <span class="st">"%Y-%m-%d"</span>) <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><img src="images/Screenshot 2023-12-15 at 12.42.31 PM.png" class="img-fluid"></p>
<p>Notice the periodic gaps in the winter. After doing some research, I found that no samples were taken due to snow pack. This gap in observations is likely to cause biases in our data, as it omits a key season in our dataset. Due to these gaps, it is difficult to perform a time series analysis &amp; decompose seasonality effects.</p>
<p>Now some box plots and violin plots to observe the distribution of the soil data averaged daily by treatment type, without the time component.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>box_vio <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data=</span>co2flux_avgs, <span class="fu">aes</span>(<span class="at">x =</span> treatment, <span class="at">y =</span> avg_co2, <span class="at">col =</span> treatment)) <span class="sc">+</span> <span class="fu">geom_violin</span>()<span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="at">width=</span><span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"Plot type"</span>) <span class="sc">+</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">"CO2 flux, μmol/(m²·s) "</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><img src="images/Screenshot 2023-12-15 at 1.34.36 PM.png" class="img-fluid"></p>
<p>The box-violin plot reveals that our data is a little bit right skewed, but mostly normal.</p>
<p>Joining soil temperature and moisture data to the co2flux daily averages</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#soiltemp_df at this point is the dataframe of averaged plot temperatures (averaging across all treatment plots)</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>soiltemp_df_avgs <span class="ot">&lt;-</span> soiltemp_df_avgs <span class="sc">%&gt;%</span> <span class="fu">rename</span>( <span class="st">"C"</span> <span class="ot">=</span> ctrl.avgT_daily, <span class="st">"H"</span> <span class="ot">=</span> treatment.avgT_daily)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>soiltemp_df_avgs <span class="ot">&lt;-</span> soiltemp_df_avgs <span class="sc">%&gt;%</span> reshape2<span class="sc">::</span><span class="fu">melt</span>(<span class="at">id =</span> <span class="st">"date"</span>) </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>soiltemp_df_avgs <span class="ot">&lt;-</span> soiltemp_df_avgs <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">treatment =</span> variable)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co">#joining the two datasets by treatment and date </span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">merge</span>(co2flux_avgs, soiltemp_df_avgs, <span class="at">by=</span> <span class="fu">c</span>(<span class="st">"date"</span>, <span class="st">"treatment"</span>))</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> result <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">avg_temp =</span> value)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>result<span class="sc">$</span>month <span class="ot">&lt;-</span> <span class="fu">format</span>(result<span class="sc">$</span>date, <span class="st">"%m"</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>result<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="fu">format</span>(result<span class="sc">$</span>date, <span class="st">"%Y"</span>)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>daily_avgs <span class="ot">&lt;-</span> result </span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(daily_avgs, <span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        date treatment  avg_co2 avg_moisture avg_temp month year
1 2003-06-10         C 127.8928           NA  13.7900    06 2003
2 2003-06-10         H 205.8222           NA  18.4245    06 2003
3 2003-07-15         C 189.5994    0.2834956  16.9050    07 2003
4 2003-07-15         H 211.0739    0.2039870  21.9360    07 2003
5 2003-08-11         C 273.7239    0.2994390  20.3925    08 2003
6 2003-08-11         H 293.6311    0.2518817  23.2730    08 2003</code></pre>
</div>
</div>
<section id="averaging-by-month-or-year" class="level3">
<h3 class="anchored" data-anchor-id="averaging-by-month-or-year">Averaging by month or year?</h3>
<p>While taking averages over time will be necessary, it is important to consider which time scale will be most appropriate. While yearly averages are most accurate in terms of smoothing out seasonal variability, the trade-off is the small sample size. Taking monthly averages, on the other-hand, will give a larger sample to work with at the manageable cost of higher variability. We first group data by month and average, then plot.</p>
<div class="cell" data-warnings="false">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#grouping data by month</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>monthly_avgs <span class="ot">&lt;-</span> daily_avgs <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(year, month, treatment) <span class="sc">%&gt;%</span>  <span class="fu">summarise</span>(<span class="at">avg_co2_mo =</span> <span class="fu">mean</span>(avg_co2), <span class="at">avg_moisture_mo =</span> <span class="fu">mean</span>(avg_moisture),  <span class="at">avg_temp_mo =</span> <span class="fu">mean</span>(avg_temp)) </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>monthly_avgs<span class="sc">$</span>datetime <span class="ot">&lt;-</span> <span class="fu">ym</span>(<span class="fu">paste</span>(monthly_avgs<span class="sc">$</span>year, monthly_avgs<span class="sc">$</span>month, <span class="at">sep =</span> <span class="st">"-"</span>))</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co">#plotting distribution </span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>monthly_avgs, <span class="fu">aes</span>(<span class="at">x =</span> treatment, <span class="at">y =</span> avg_co2_mo, <span class="at">color =</span> treatment)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span>  </span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"treatment type"</span>) <span class="sc">+</span> </span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">"CO2 flux, μmol/(m²·s) "</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 22 rows containing non-finite values (`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="barre_woods_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Alternatively, grouping by year:</p>
<div class="cell" data-warnings="false">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>yearly_avgs <span class="ot">&lt;-</span> daily_avgs <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(year, treatment) <span class="sc">%&gt;%</span>  <span class="fu">summarise</span>(<span class="at">avg_co2_yr =</span> <span class="fu">mean</span>(avg_co2), <span class="at">avg_moisture_yr =</span> <span class="fu">mean</span>(avg_moisture),  <span class="at">avg_temp_yr =</span> <span class="fu">mean</span>(avg_temp)) </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>yearly_avgs, <span class="fu">aes</span>(<span class="at">x =</span> treatment, <span class="at">y =</span> avg_co2_yr, <span class="at">color =</span> treatment)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"treatment type"</span>) <span class="sc">+</span> </span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">"CO2 flux, μmol/(m²·s) "</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 10 rows containing non-finite values (`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 10 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="barre_woods_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
</section>
<section id="analysis" class="level1">
<h1>Analysis</h1>
<section id="evaluating-significant-differences-in-average-co2-flux-between-treatment-and-control-plots" class="level2">
<h2 class="anchored" data-anchor-id="evaluating-significant-differences-in-average-co2-flux-between-treatment-and-control-plots">Evaluating significant differences in average CO2 flux between treatment and control plots</h2>
<p>The plots above give an intuitive idea about how yearly vs.&nbsp;monthly averaging affects the distribution of the dataset, so let’s test it using regression.</p>
<p><strong><em>Single variable, categorical model for yearly averaging</em></strong></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>single_ct_lm <span class="ot">&lt;-</span> <span class="fu">lm</span> (avg_co2_yr <span class="sc">~</span> treatment, <span class="at">data =</span> yearly_avgs)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(single_ct_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = avg_co2_yr ~ treatment, data = yearly_avgs)

Residuals:
    Min      1Q  Median      3Q     Max 
-35.859 -12.519  -2.844  12.175  47.812 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 137.5018     5.9234  23.213   &lt;2e-16 ***
treatmentH    0.7497     8.3769   0.089    0.929    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 20.52 on 22 degrees of freedom
  (10 observations deleted due to missingness)
Multiple R-squared:  0.0003639, Adjusted R-squared:  -0.04507 
F-statistic: 0.008009 on 1 and 22 DF,  p-value: 0.9295</code></pre>
</div>
</div>
<p>The results of an adjusted <span class="math inline">\(R^2 = -0.04507\)</span> and <span class="math inline">\(p = 0.9295\)</span> (equivalent to that of a two tailed t-test) reveal that there was no significant change in carbon flux between heated and treated plots. There is likely still too much variability, due to factors such as seasons and soil conditions, to determine a significant effect of the treatment. Let’s repeat this with monthly average data.</p>
<p><strong><em>Single variable, categorical model for monthly averaging</em></strong></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>single_ct_lm <span class="ot">&lt;-</span> <span class="fu">lm</span> (avg_co2_mo <span class="sc">~</span> treatment, <span class="at">data =</span> monthly_avgs)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(single_ct_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = avg_co2_mo ~ treatment, data = monthly_avgs)

Residuals:
     Min       1Q   Median       3Q      Max 
-112.641  -49.185   -6.048   43.183  180.144 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  132.169      5.958  22.183   &lt;2e-16 ***
treatmentH     5.064      8.426   0.601    0.548    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 62.2 on 216 degrees of freedom
  (22 observations deleted due to missingness)
Multiple R-squared:  0.00167,   Adjusted R-squared:  -0.002952 
F-statistic: 0.3612 on 1 and 216 DF,  p-value: 0.5485</code></pre>
</div>
</div>
<p>Averaging by month yields better (albeit, still poor) <span class="math inline">\(R^2\)</span> and <span class="math inline">\(p\)</span> values. Yearly averaging reduces the seasonal variability and tells us the overall long term effect of temperature on carbon flux, while monthly averaging give us the option of considering the effects of seasonality on our data. For the purposes of finding a linear regression to describe the data, we will choose the dataset with variables averaged monthly and will run a single variable, categorical regression.</p>
</section>
</section>
<section id="defining-a-regression-model" class="level1">
<h1>Defining a regression model</h1>
<p>Once again, we will define a single variable categorical regression model with only monthly average data. We regress CO2 flux on treatment type.</p>
<section id="model-0-single-variable-categorical-regression" class="level2">
<h2 class="anchored" data-anchor-id="model-0-single-variable-categorical-regression">Model 0) Single variable, categorical regression</h2>
<p>Our null hypothesis (what we aim to reject based on the results of the regression) is based on the possibility that heat treatment has no effect on mean monthly carbon flux as compared to a control plot. This is a good moment to define both our null and alternative hypotheses:</p>
<ul>
<li><p><strong>Null hypothesis:</strong> there is no significant difference in mean monthly carbon flux between control and heat-applied (treatment) plots.</p></li>
<li><p><strong>Alternative hypothesis:</strong> there is a significant difference in mean monthly carbon flux between control and heat-applied (treatment) plots</p></li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>model_0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(avg_co2_mo <span class="sc">~</span> treatment, <span class="at">data =</span> monthly_avgs)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>model_0_plt <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(monthly_avgs, <span class="fu">aes</span>(<span class="at">y =</span> avg_co2_mo, <span class="at">x =</span> treatment, <span class="at">color =</span> treatment)) <span class="sc">+</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_categorical_model</span>() <span class="sc">+</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"treatment type"</span>) <span class="sc">+</span> </span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="st">"CO2 flux, μmol/(m²·s) "</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><img src="images/Screenshot 2023-12-15 at 2.25.58 PM.png" class="img-fluid" width="455"></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(model_0))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = avg_co2_mo ~ treatment, data = monthly_avgs)

Residuals:
     Min       1Q   Median       3Q      Max 
-112.641  -49.185   -6.048   43.183  180.144 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  132.169      5.958  22.183   &lt;2e-16 ***
treatmentH     5.064      8.426   0.601    0.548    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 62.2 on 216 degrees of freedom
  (22 observations deleted due to missingness)
Multiple R-squared:  0.00167,   Adjusted R-squared:  -0.002952 
F-statistic: 0.3612 on 1 and 216 DF,  p-value: 0.5485</code></pre>
</div>
</div>
<p><img src="images/Screenshot 2023-12-15 at 12.58.52 PM.png" class="img-fluid" width="432"></p>
<p>In summary, this single variable, categorical regression model regressing monthly carbon flux on treatment type reveals:</p>
<ul>
<li><p>….a p-value of 0.548, suggesting that there is not enough evidence to conclude that there is a significant relationship between treatment type and carbon flux.</p></li>
<li><p>…. an adjusted R-squared of -0.0029, suggesting that the model, with treatment type as the predictor, is not explaining much of the variability in carbon flux, and the model may not be a good fit.</p></li>
<li><p>…. that the application of 5 degrees Celsius of heat increases the carbon flux by <span class="math inline">\(5 \dfrac{umol CO_2}{m^2 * s}\)</span>.</p></li>
</ul>
</section>
<section id="model-1-multiple-regression" class="level2">
<h2 class="anchored" data-anchor-id="model-1-multiple-regression">Model 1) multiple regression</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#model_1</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>model_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(avg_co2_mo <span class="sc">~</span> treatment <span class="sc">+</span> month <span class="sc">+</span> avg_temp_mo <span class="sc">+</span> avg_moisture_mo , <span class="at">data =</span> monthly_avgs)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = avg_co2_mo ~ treatment + month + avg_temp_mo + avg_moisture_mo, 
    data = monthly_avgs)

Residuals:
    Min      1Q  Median      3Q     Max 
-81.959 -14.531  -0.398  15.906  76.790 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      -81.079     14.286  -5.676 5.07e-08 ***
treatmentH       -37.591      6.846  -5.491 1.26e-07 ***
month05            1.304     10.100   0.129   0.8974    
month06           22.984     12.075   1.904   0.0585 .  
month07           45.680     14.909   3.064   0.0025 ** 
month08           32.498     14.498   2.241   0.0261 *  
month09            8.089     12.809   0.632   0.5285    
month10           13.177      9.031   1.459   0.1462    
month11           20.416      9.011   2.266   0.0246 *  
month12           42.505     21.701   1.959   0.0516 .  
avg_temp_mo       10.744      1.121   9.585  &lt; 2e-16 ***
avg_moisture_mo  210.278     32.260   6.518 6.18e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 27.91 on 191 degrees of freedom
  (37 observations deleted due to missingness)
Multiple R-squared:  0.8086,    Adjusted R-squared:  0.7975 
F-statistic: 73.34 on 11 and 191 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>This multiple variable regression model regressing the average monthly carbon flux on treatment type, month, average monthly temperature, and average moisture reveals:</p>
<ul>
<li><p>…. a p-value of <span class="math inline">\(&lt; 2.2*10^{-16}\)</span>, suggesting that there is enough evidence to conclude that there is a significant relationship between carbon flux and the regressed variables.</p></li>
<li><p>…. an adjusted R-squared of 0.79, suggesting that the model, with treatment type as the predictor, is explaining much (79.75) of the variability in carbon flux, and the model may be a good fit!</p></li>
<li><p>…. that treatment, three months, average monthly temperature, and average monthly moisture are variables that contribute significantly (p <span class="math inline">\(&lt; 0.05\)</span>) to the model.</p></li>
</ul>
</section>
<section id="addressing-ommited-variables-bias" class="level2">
<h2 class="anchored" data-anchor-id="addressing-ommited-variables-bias">Addressing ommited variables bias</h2>
<p>Before we move on, we need to consider the possibility of omitted variables, so as to avoid omitted variable bias.</p>
<p>My guess is that there exists dependency between moisture and temperature. Let’s plot moisture and temperature to see if there’s a possibility of dependency between them.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create scatter plot with line of best fit</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>ovb <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(monthly_avgs, <span class="fu">aes</span>(<span class="at">x=</span>avg_temp_mo, <span class="at">y=</span>avg_moisture_mo)) <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">'lm'</span>, <span class="at">se=</span><span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"coral"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><img src="images/Screenshot 2023-12-15 at 1.14.28 PM.png" class="img-fluid" width="516"></p>
<p>From this graph, we can see that there is most likely a negative relationship between temperature and moisture. Our second iteration of the model will take these factors into consideration</p>
</section>
<section id="model-2-multiple-regression-with-interaction-term" class="level2">
<h2 class="anchored" data-anchor-id="model-2-multiple-regression-with-interaction-term">Model 2) multiple regression with interaction term</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>model_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(avg_co2_mo <span class="sc">~</span> treatment <span class="sc">+</span> month <span class="sc">+</span> avg_temp_mo <span class="sc">+</span> avg_moisture_mo <span class="sc">+</span> avg_temp_mo<span class="sc">:</span>avg_moisture_mo, <span class="at">data =</span> monthly_avgs)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = avg_co2_mo ~ treatment + month + avg_temp_mo + avg_moisture_mo + 
    avg_temp_mo:avg_moisture_mo, data = monthly_avgs)

Residuals:
   Min     1Q Median     3Q    Max 
-73.18 -15.94  -1.74  17.78  71.78 

Coefficients:
                            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    3.698     24.609   0.150 0.880703    
treatmentH                   -37.063      6.574  -5.638 6.16e-08 ***
month05                       -3.264      9.759  -0.334 0.738417    
month06                       17.091     11.679   1.463 0.145019    
month07                       42.181     14.339   2.942 0.003669 ** 
month08                       30.328     13.929   2.177 0.030696 *  
month09                        4.189     12.334   0.340 0.734514    
month10                        6.302      8.827   0.714 0.476147    
month11                       19.382      8.655   2.240 0.026279 *  
month12                       20.599     21.493   0.958 0.339071    
avg_temp_mo                    5.877      1.592   3.691 0.000291 ***
avg_moisture_mo             -134.063     88.584  -1.513 0.131838    
avg_temp_mo:avg_moisture_mo   21.593      5.204   4.149 5.03e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 26.79 on 190 degrees of freedom
  (37 observations deleted due to missingness)
Multiple R-squared:  0.8245,    Adjusted R-squared:  0.8134 
F-statistic: 74.37 on 12 and 190 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>With an adjusted <span class="math inline">\(R^2 = 0.8134\)</span>, and a p-value of <span class="math inline">\(&lt; 2.2 * 10^{-16}\)</span>, this model is looking pretty good! Coefficients that are significant are: treatment type, three months of the year, average monthly temperature, and the interaction between average monthly moisture and average monthly temperature. We see that when all independent variables are equal, the average monthly carbon flux on the control plot is <span class="math inline">\(3.69 \dfrac{umol CO_2}{m^2 * s}\)</span>.</p>
<p>Breaking this down, we can say that this model explains 81.34% of the variation in carbon flux, and that there is an almost zero probability that the observed carbon flux data occurred by random chance alone, assuming the null hypothesis is true. However, this model simultaneously suggests that the addition of treatment reduces the average carbon flux by $ -37 $. This value being negative is a little counter-intuitive, since in our single variable, categorical model demonstrates an overall positive effect. This suggests that the addition of more variables may explain our model better mathematically, but more work needs to be done to evaluate the scientific robustness of this model.</p>
</section>
<section id="limitations-next-steps" class="level2">
<h2 class="anchored" data-anchor-id="limitations-next-steps">Limitations + next steps</h2>
<p>This statistical analysis was limited by a variety of factors, including periodic sampling gaps during the winter months, which accounts for a quarter of the year. These gaps significantly introduced biases into our results. To adjust for this bias, the study by Dr.&nbsp;Jerry Melillo et Al. fills in the gaps by leveraging a model that estimates carbon flux based on sampled ambient air temperature. Unfortunately, the scope of this project did not encompass statistical data modeling. Due to these gaps, I was unable to perform a time series analysis that would have helped decompose seasonality effects in the data. It would be interesting to perform such a process to see what difference including winter data could bring. Additionally, I would be interested to incorporate more parameters into the model, such as nitrogen availability, leaf-litter composition, and plant-root density.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>[<a href="https://www.wri.org/insights/ipcc-climate-report">1</a>] Levin, K. (August 9, 2021). IPCC’s 2021 Climate Report. World Resources Institute. Accessed December 15, 2023. URL: https://www.wri.org/insights/ipcc-climate-report</p>
<p>[<a href="https://portal.edirepository.org/nis/metadataviewer?packageid=knb-lter-hfr.18.34">2</a>] EDI Data Package Summary: Barre Woods Soil Warming Experiment at Harvard Forest since 2001. Retrieved from: https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-hfr.18.34</p>
<p>[<a href="https://harvardforest.fas.harvard.edu/news/results-20-year-soil-warming-experiment">3</a>] Potier, B. (2013). Warmer Soils Release More CO2 to Atmosphere; Effect Stabilizes Over Long Term. Retrieved:https://harvardforest.fas.harvard.edu/sites/default/files/Harvard%20Forest_Frey_Nature%20Climate%20Change_press%20release%202013.pdf</p>
<p>[<a href="https://harvardforest.fas.harvard.edu/soil-warming-experiment">4</a>] Soil Warming Experiments, Harvard Forest. Accessed Dec 10, 2023. URL: https://harvardforest.fas.harvard.edu/soil-warming-experiment</p>
<p>[5] Frey, S. and J. Melillo. 2023. Barre Woods Soil Warming Experiment at Harvard Forest since 2001 ver 34. Environmental Data Initiative. https://doi.org/10.6073/pasta/9e34836122d20a123ff2c38d95527e28 (Accessed 2023-12-15).</p>
<p>[6] Melillo, Jerry et Al. Soil warming, carbon–nitrogen interactions, and forest carbon budgets. PNAS Vol. 108, Volume 23. Published May 23, 2011.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
 Copyright 2023, Flora Hamilton
  </li>  
</ul>
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
      <i class="bi bi-github" role="img">
</i> 
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>