{
  "hash": "bc598a08b78602098fce82e13c671285",
  "result": {
    "markdown": "---\ntitle: '2021 Texas Blackout'\ndescription: 'Analyzing affected areas & socioeconomic factors that influenced recovery'\nauthor: \"Flora Hamilton\"\ndate: \"2022-10-26\"\noutput:\n    html_document:\n      print_df: paged\n      toc: yes\n      toc_depth: 4\n      toc_float: yes\ndraft: false\n---\n\n\n\n\n![](images/Screenshot 2023-12-14 at 12.03.11 AM.png)\n\n# Texas Blackouts\n\n### Analyzing the Effects of the Texas February 2021 Storm on the Houston metropolitan Area\n\n📦 repo link \\| https://github.com/floraham/texas-blackout\n\n## Context\n\n\"In February 2021, Texas faced a significant power crisis resulting from three severe winter storms that swept across the United States on February 10--11, 13--17, and 15--20.\"[^1] For additional insights, explore these [engineering](https://www.youtube.com/watch?v=08mwXICY4JM&ab_channel=PracticalEngineering) and [political](https://www.youtube.com/watch?v=Zcrsgdl_hP0&ab_channel=Vox) perspectives.\n\n[^1]: Wikipedia. 2021. \"2021 Texas power crisis.\" Last modified October 2, 2021. <https://en.wikipedia.org/wiki/2021_Texas_power_crisis>.\n\n## The objectives and methods:\n\nEstimate the number of households in Houston that experienced power loss due to the initial two storms. To determine the count of homes affected by power outages, we will spatially join these areas with \\[OpenStreetMap\\](https://www.openstreetmap.org/#map=4/38.01/-95.84) data on buildings and roads.\n\nInvestigate whether socioeconomic factors serve as predictors of community recovery from a power outage. For the exploration of potential socioeconomic factors influencing recovery, the analysis will be linked with data from the US Census Bureau.\n\nThis analysis will rely on remotely-sensed night lights data acquired from the [Visible Infrared Imaging Radiometer Suite (VIIRS)](https://en.wikipedia.org/wiki/Visible_Infrared_Imaging_Radiometer_Suite) aboard the Suomi satellite. Specifically, we will use the VNP46A1 to identify variations in night lights before and after the storms as a method to identify areas that lost electrical power.\n\n## Data\n\n#### Night lights ✨\n\nWe use NASA's Worldview to explore the data around the day of the storm. There are several days with too much cloud cover to be useful, but 2021-02-07 and 2021-02-16 provide two clear, contrasting images to visualize the extent of the power outage in Texas.\n\nVIIRS data is distributed through NASA's [Level-1 and Atmospheric Archive & Distribution System Distributed Active Archive Center (LAADS DAAC)](https://ladsweb.modaps.eosdis.nasa.gov/). Many NASA Earth data products are distributed in 10x10 degree tiles in sinusoidal equal-area projection. Tiles are identified by their horizontal and vertical position in the grid. Houston lies on the border of tiles h08v05 and h08v06. We therefore need to download two tiles per date.\n\nThe following files had been sub-setted & stored in the `VNP46A1` folder.\n\n-   `VNP46A1.A2021038.h08v05.001.2021039064328.tif`: tile h08v05, collected on 2021-02-07\n-   `VNP46A1.A2021038.h08v06.001.2021039064329.tif`: tile h08v06, collected on 2021-02-07\n-   `VNP46A1.A2021047.h08v05.001.2021048091106.tif`: tile h08v05, collected on 2021-02-16\n-   `VNP46A1.A2021047.h08v06.001.2021048091105.tif`: tile h08v06, collected on 2021-02-16\n\n#### Roads 🛣️  `gis_osm_roads_free_1.gpkg`\n\nTypically highways account for a large portion of the night lights observable from space (see Google's [Earth at Night](https://earth.google.com/web/@27.44405464,-84.7693044,206.63660162a,8916361.52264659d,35y,0h,0t,0r/data=CiQSIhIgMGY3ZTJkYzdlOGExMTFlNjk5MGQ2ZjgxOGQ2OWE2ZTc)). To minimize falsely identifying areas with reduced traffic as areas without power, we will ignore areas near highways.\n\n[OpenStreetMap (OSM)](https://planet.openstreetmap.org/) is a collaborative project which creates publicly available geographic data of the world. Ingesting this data into a database where it can be subsetted and processed is a large undertaking. Fortunately, third party companies redistribute OSM data. We used [Geofabrik's download sites](https://download.geofabrik.de/) to retrieve a shapefile of all highways in Texas and prepared a Geopackage (`.gpkg` file) containing just the subset of roads that intersect the Houston metropolitan area. \n\n#### Houses 🏠 `gis_osm_buildings_a_free_1.gpkg`\n\nWe also obtain building data from OpenStreetMap. We again downloaded from Geofabrick and prepared a GeoPackage containing only houses in the Houston metropolitan area.\n\n#### Socioeconomic 👨‍👩‍👧‍👦 `ACS_2019_5YR_TRACT_48.gdb`\n\nWe cannot readily get socioeconomic information for every home, so instead we obtained data from the [U.S. Census Bureau's American Community Survey](https://www.census.gov/programs-surveys/acs) for census tracts in 2019. The *folder* `ACS_2019_5YR_TRACT_48.gdb` is an ArcGIS [\"file geodatabase\"](https://desktop.arcgis.com/en/arcmap/latest/manage-data/administer-file-gdbs/file-geodatabases.htm), a multi-file proprietary format that's roughly analogous to a GeoPackage file. We can use `st_layers()` to explore the contents of the geodatabase. Each layer contains a subset of the fields documents in the [ACS metadata](https://www2.census.gov/geo/docs/maps-data/data/tiger/prejoined/ACSMetadata2011.txt). The geodatabase contains a layer holding the geometry information, separate from the layers holding the ACS attributes. You have to combine the geometry with the attributes to get a feature layer that `sf` can use.\n\n## Project Roadmap\n\nBelow is an outline of the steps taken to achieve the objectives.\n\n## Find locations of blackouts\n\nFor improved computational efficiency and easier inter-operability with `sf`, we use the `stars` package for raster handling.\\\n\n##### combine the data\n\n-   We first read in night lights tiles, then combine tiles into a single `stars` object for each date (2021-02-07 and 2021-02-16) using `st_mosaic.`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sf)\nlibrary(stars)\nlibrary(tmap)\nlibrary(raster)\nlibrary(terra)\nlibrary(dplyr)\nlibrary(ggplot2)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## Read in all four night lights tiles, in folder VNP46A1, using the package \"stars\" \n\ntile1_2021_02_07 = read_stars(\"~/dev/eds223/assignment-3-floraham/data/VNP46A1/VNP46A1.A2021038.h08v05.001.2021039064328.tif\", package = \"stars\")\n \ntile2_2021_02_07 = read_stars(\"~/dev/eds223/assignment-3-floraham/data/VNP46A1/VNP46A1.A2021038.h08v06.001.2021039064329.tif\", package = \"stars\")\n\ntile3_2021_02_16 =  read_stars(\"~/dev/eds223/assignment-3-floraham/data/VNP46A1/VNP46A1.A2021047.h08v05.001.2021048091106.tif\", package = \"stars\")\n\ntile4_2021_02_16 =  read_stars(\"~/dev/eds223/assignment-3-floraham/data/VNP46A1/VNP46A1.A2021047.h08v06.001.2021048091105.tif\", package = \"stars\")\n\n\n# combine tiles into single stars object for each date (2021-02-07 and 2021-02-16), using st_mosaic \ncombined_02_07 = st_mosaic(tile1_2021_02_07, tile2_2021_02_07)\ncombined_02_16 = st_mosaic(tile3_2021_02_16, tile4_2021_02_16)\n```\n:::\n\n\n##### create a blackout mask\n\n-   We then find the change in night lights intensity (presumably) caused by the storm, and reclassify the difference raster, assuming that any location that experienced a drop of more than 200 nW cm^-2^sr^-1^ experienced a blackout. Then we assign `NA` to all locations that experienced a drop of *less* than 200 nW cm^-2^sr.^-1^\\\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#find the change in night lights intensity (presumably) caused by the storm by calculating the light difference between the two dates \ndifference <- combined_02_07 - combined_02_16\n\n\n#check out difference in night lights intensity \nplot(difference)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\ndownsample set to 6\n```\n:::\n\n::: {.cell-output-display}\n![](texas-blackout_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#reclassify the difference raster, assuming that any location that experienced a drop of more than 200 nW cm-2sr-1 experienced a blackout by assigning NA to locations that experienced drop of less than 200 nW cm-2sr-1\n\n#assigning all the houses that experienced a drop of 200 and more to a blackout mask.\nmask_blackout <- difference > 200 \nmask_blackout[mask_blackout == FALSE]  <- NA\n```\n:::\n\n\n##### vectorize the mask\n\nWe use `st_as_sf()` to vectorize the blackout mask and fix any invalid geometries using `st_make_valid.`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nblackout_mask_vector <- st_as_sf(mask_blackout) %>% st_make_valid() ##can plot() to check out what the blackout mask looks like \n```\n:::\n\n\n##### crop the vectorized map to our region of interest\n\n-   We first define the Houston metropolitan area with the following coordinates : (-96.5, 29), (-96.5, 30.5), (-94.5, 30.5), (-94.5, 29) and then turn these coordinates into a polygon using `st_polygon.`\n-   Then we convert the polygon into a simple feature collection using `st_sfc()` and assign a CRS, making sure that the polygon is in the same CRS and crop (spatially subset) the blackout mask to our region of interest. Lastly we re-project the cropped blackout dataset to EPSG:3083 (NAD83 / Texas Centric Albers Equal Area). \\\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#crop the vectorized map to our region of interest using polygon of Houston's coordinates \nhouston_polygon <- st_polygon(list(rbind(c(-96.5,29), c(-96.5,30.5), c(-94.5, 30.5), c(-94.5,29), c(-96.5,29))))\n\n\n#convert the polygon into a simple feature collection using st_sfc() and assign the CRS 4326, which is the same as the night lights data\nhouston_border_sf <- st_sfc(houston_polygon, crs = st_crs(mask_blackout))\n\n\n##inspect the polygon crs to make sure the crs is 4326, nightlights dataset\nst_crs(houston_border_sf) == st_crs(mask_blackout)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n\n```{.r .cell-code}\n# spatially subset the blackout mask to the Houston Area\nhouston_blackout <- blackout_mask_vector[houston_border_sf, ,]\n\n\n#re-project the cropped blackout dataset to EPSG:3083 (NAD83 / Texas Centric Albers Equal Area)\nhouston_blackout <- st_transform(houston_blackout, crs = 'EPSG:3083')\n\n## transform to sf object\nfinal_houston_blackout <- st_as_sf(houston_blackout)\n\n#verify that it's an sf object \nclass(final_houston_blackout)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"sf\"         \"data.frame\"\n```\n:::\n\n```{.r .cell-code}\n##verify that the final, transformed sf houston blackout dataset is 3083 \nst_crs(final_houston_blackout) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCoordinate Reference System:\n  User input: EPSG:3083 \n  wkt:\nPROJCRS[\"NAD83 / Texas Centric Albers Equal Area\",\n    BASEGEOGCRS[\"NAD83\",\n        DATUM[\"North American Datum 1983\",\n            ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4269]],\n    CONVERSION[\"Texas Centric Albers Equal Area\",\n        METHOD[\"Albers Equal Area\",\n            ID[\"EPSG\",9822]],\n        PARAMETER[\"Latitude of false origin\",18,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8821]],\n        PARAMETER[\"Longitude of false origin\",-100,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8822]],\n        PARAMETER[\"Latitude of 1st standard parallel\",27.5,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8823]],\n        PARAMETER[\"Latitude of 2nd standard parallel\",35,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8824]],\n        PARAMETER[\"Easting at false origin\",1500000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8826]],\n        PARAMETER[\"Northing at false origin\",6000000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8827]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"State-wide spatial data presentation requiring true area measurements.\"],\n        AREA[\"United States (USA) - Texas.\"],\n        BBOX[25.83,-106.66,36.5,-93.5]],\n    ID[\"EPSG\",3083]]\n```\n:::\n:::\n\n\n##### exclude highways from blackout mask\n\nThe roads geopackage includes data on roads other than highways. However, we can avoid reading in data we don't need by taking advantage of `st_read`'s ability to subset using a SQL query. First, we load just highway data from geopackage using `st_read and`reproject data to EPSG:3083, identifying areas within 200m of all highways using `st_buffer. st_buffer` produces undissolved buffers, so we use `st_union` to dissolve them. Then we find areas that experienced blackouts that are further than 200m from a highway.\n\n**The SQL query we will use is:**\n\n`query <- \"SELECT * FROM gis_osm_roads_free_1 WHERE fclass='motorway'\"`\\\n`highways <- st_read(\"data/gis_osm_roads_free_1.gpkg\", query = query)`\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Read in highway data from roads using SQL query ##\nquery <- \"SELECT * FROM gis_osm_roads_free_1 WHERE fclass='motorway'\"\nhighways <- st_read(\"~/dev/eds223/assignment-3-floraham/data/gis_osm_roads_free_1.gpkg\", query = query)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# reproject data to EPSG:3083 \nhighways_3038 <- st_transform(highways, crs=\"EPSG:3083\")\n\n##verify it's the right crs\nst_crs(highways_3038)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCoordinate Reference System:\n  User input: EPSG:3083 \n  wkt:\nPROJCRS[\"NAD83 / Texas Centric Albers Equal Area\",\n    BASEGEOGCRS[\"NAD83\",\n        DATUM[\"North American Datum 1983\",\n            ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4269]],\n    CONVERSION[\"Texas Centric Albers Equal Area\",\n        METHOD[\"Albers Equal Area\",\n            ID[\"EPSG\",9822]],\n        PARAMETER[\"Latitude of false origin\",18,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8821]],\n        PARAMETER[\"Longitude of false origin\",-100,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8822]],\n        PARAMETER[\"Latitude of 1st standard parallel\",27.5,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8823]],\n        PARAMETER[\"Latitude of 2nd standard parallel\",35,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8824]],\n        PARAMETER[\"Easting at false origin\",1500000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8826]],\n        PARAMETER[\"Northing at false origin\",6000000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8827]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"State-wide spatial data presentation requiring true area measurements.\"],\n        AREA[\"United States (USA) - Texas.\"],\n        BBOX[25.83,-106.66,36.5,-93.5]],\n    ID[\"EPSG\",3083]]\n```\n:::\n\n```{.r .cell-code}\n# identify areas within 200m of all highways using st_buffer. Use st_union to dissolve overlapping polygons. \na_near_hwys <- st_buffer(highways_3038, dist = 200) %>% st_union()\n\n# find areas that experienced blackouts that are further than 200m from a highway by spacially subsetting houston blackout areas to ones near highways, and taking st_difference of that. \nblackouts_far_hwy_houston <- final_houston_blackout[a_near_hwys, , op = st_difference] \n\n\n#plot to see what it looks like \nplot(blackouts_far_hwy_houston)\n```\n\n::: {.cell-output-display}\n![](texas-blackout_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n## Find homes impacted by blackouts\n\n##### load buildings data\n\nWe load buildings dataset using `st_read` and the following SQL query to select only residential buildings. We first reproject data to EPSG:3083.\n\nThe SQL query we will use is:\n\n`SELECT *`  `FROM gis_osm_buildings_a_free_1`\\\n`WHERE (type IS NULL AND name IS NULL)`\\\n`OR type in ('residential', 'apartments', 'house', 'static_caravan', 'detached')`\\\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#load buildings dataset using st_read and the following SQL query to select only residential buildings\n\nquery_buildings <- \"SELECT * FROM gis_osm_buildings_a_free_1 WHERE (type IS NULL AND name IS NULL) OR type in ('residential', 'apartments', 'house', 'static_caravan', 'detached')\"\n\nbuildings <- st_read(\"~/dev/eds223/assignment-3-floraham/data/gis_osm_buildings_a_free_1.gpkg\", query = query_buildings)\n```\n:::\n\n\n##### find homes in blackout areas\n\n-   filter to homes within blackout areas\\\n-   count number of impacted **homes**\\\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##check CRS's are the same \nst_crs(buildings) == st_crs(blackouts_far_hwy_houston)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] FALSE\n```\n:::\n\n```{.r .cell-code}\n##transform buildings crs \nbuildings <- st_transform(buildings, crs = st_crs(blackouts_far_hwy_houston))\n\n# filtering the houses data with the blackout mask\nbuildings_blackout <- buildings[blackouts_far_hwy_houston, drop = FALSE]\n\n## View the data frame for inspection \nView(buildings_blackout)\n\n#count number of impacted homes\nprint(paste0(nrow(buildings_blackout), \" Houston homes experienced power outage due to the Texas storms in Feburary, 2021\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"164867 Houston homes experienced power outage due to the Texas storms in Feburary, 2021\"\n```\n:::\n:::\n\n\n## Investigate socioeconomic factors\n\n##### load ACS data\n\nTo set up for loading, we use `st_read()` to load the geodatabase layers and geometries are stored in the `ACS_2019_5YR_TRACT_48_TEXAS` layer. The income data is stored in the `X19_INCOME` layer, so we select the median income field `B19013e1 and`reproject data to EPSG:3083. \\\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncensus <- st_read(\"~/dev/eds223/assignment-3-floraham/data/ACS_2019_5YR_TRACT_48_TEXAS.gdb\",  layer = \"ACS_2019_5YR_TRACT_48_TEXAS\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nReading layer `ACS_2019_5YR_TRACT_48_TEXAS' from data source \n  `/Users/florahamilton/dev/eds223/assignment-3-floraham/data/ACS_2019_5YR_TRACT_48_TEXAS.gdb' \n  using driver `OpenFileGDB'\nSimple feature collection with 5265 features and 15 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -106.6456 ymin: 25.83716 xmax: -93.50804 ymax: 36.5007\nGeodetic CRS:  NAD83\n```\n:::\n\n```{.r .cell-code}\nincome <- st_read(\"~/dev/eds223/assignment-3-floraham/data/ACS_2019_5YR_TRACT_48_TEXAS.gdb\", layer = \"X19_INCOME\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nReading layer `X19_INCOME' from data source \n  `/Users/florahamilton/dev/eds223/assignment-3-floraham/data/ACS_2019_5YR_TRACT_48_TEXAS.gdb' \n  using driver `OpenFileGDB'\n```\n:::\n\n```{.r .cell-code}\n#select median income field B19013e1\nmedian_income <- income %>% dplyr::select(GEOID, B19013e1) \n```\n:::\n\n\n##### determine which census tracts experienced blackouts\n\n-   join the income data to the census tract geometries by joining by geometry ID and spatially join census tract data with buildings determined to be impacted by blackouts, then find which census tracts had blackouts. \\\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#determine which census tracts experienced blackouts \n#Join the income data to the census tract geometries. Join by geometry ID\nmedian_income_df <- median_income %>% rename(GEOID_Data = GEOID,\n         median_income = B19013e1) \n\n\n##check types to varify that they are the same class \nclass(median_income_df$GEOID_Data) == class(census$GEOID_Data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n\n```{.r .cell-code}\njoined_income_census <- left_join(census, \n                         median_income_df, \n                         by = \"GEOID_Data\")\n\n\n## filter census data by buildings determined to be impacted by blackouts. \n\n# transforming both objects to the correct crs\njoined_income_census <- st_transform(joined_income_census, crs = st_crs(census))\nbuildings_blackout <- st_transform(buildings_blackout, crs = st_crs(census))\n\n#check that they are the same crs \nst_crs(joined_income_census) == st_crs(buildings_blackout)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n\n```{.r .cell-code}\n## filtering and mutating to add a blackout column for affected tracts \ncensus_blackout <- joined_income_census[buildings_blackout,]%>% mutate(blackout = 'Y')\n\nprint(paste0(nrow(census_blackout), \" census tracts had blackouts\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"778 census tracts had blackouts\"\n```\n:::\n\n```{.r .cell-code}\n## Since we have blackout status of Y indicated, we will want to indicate \"N\" for no-blackout areas as well, for full dataset. \n\n#census_income_cropped combined with census_blackout\ncensus_Y_N <- full_join(as.data.frame(joined_income_census), as.data.frame(census_blackout))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nJoining with `by = join_by(STATEFP, COUNTYFP, TRACTCE, GEOID, NAME, NAMELSAD,\nMTFCC, FUNCSTAT, ALAND, AWATER, INTPTLAT, INTPTLON, Shape_Length, Shape_Area,\nGEOID_Data, median_income, Shape)`\n```\n:::\n\n```{.r .cell-code}\ncensus_Y_N$blackout[is.na(census_Y_N$blackout)] = \"N\" \n\n#check the class \nclass(census_Y_N)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"data.frame\"\n```\n:::\n\n```{.r .cell-code}\n## make sure it's an sf object \ncensus_Y_N <- st_as_sf(census_Y_N)\n\n#check census_Y_N class, that it's a dataframe. \nclass(census_Y_N)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"sf\"         \"data.frame\"\n```\n:::\n:::\n\n\n##### compare incomes of impacted tracts to unimpacted tracts\n\n-   create a map of median income by census tract, designating which tracts had blackouts\n-   plot the distribution of income in impacted and unimpacted tracts\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#join income data to the census tract geometries and crop to region of interest\ncensus_income_geom <- left_join(census, median_income_df, \n                         by = \"GEOID_Data\") %>% st_transform(3083) #this is texas#\nhouston_border_sf <- houston_border_sf %>% st_transform(3083)\n\n\n#spatial crop joined census data to houston border \ncensus_income_geom_cropped <- census_income_geom[houston_border_sf, op = st_intersects] \n\n\n## use tmap to plot income distribution and affected areas. Make graph aesthetics. \ntmap_mode(\"plot\")\ntm_shape(census_income_geom_cropped) + \n  tm_graticules() + \n  tm_polygons(\"median_income\", palette= \"-viridis\", title = \"Median income\") + \n  tm_shape(census_blackout) + tm_dots(size = 0.4, alpha = 0.5) + \n  tm_title( \"Distribution of Med. Income & blackout status in Houston\") +\n  tm_scalebar(position = c(\"RIGHT\", \"BOTTOM\")) + \n  tm_compass(position = c(\"LEFT\", \"BOTTOM\")) + \n  tm_xlab(\"Longitude\", size = 0.5) + \n  tm_ylab(\"Latitude\", rotation = 90, size = 0.5) \n```\n\n::: {.cell-output-display}\n![](texas-blackout_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#plot histogram of the distribution of median incomes of homes by blackout status \n\n#Plot from one dataset so that ggplot can plot both datasets on one axis & autogenerate legend\ncensus_Y_N_houston <- census_Y_N %>% st_transform(3083) \nhouston_border_sf <- houston_border_sf %>% st_transform(3083)\ncensus_Y_N_houston <- census_Y_N_houston[houston_border_sf, op = st_intersects] \n\n\nggplot(census_Y_N_houston, aes(median_income)) + geom_histogram(aes(color = blackout, fill = blackout), bins = 50) + ggtitle(\"Distribution of median income of homes in Houston by blackout status\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 10 rows containing non-finite values (`stat_bin()`).\n```\n:::\n\n::: {.cell-output-display}\n![](texas-blackout_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## Doing other statistical explorations\n\n# plotting the comparison data via geom jitter plot\nggplot(census_Y_N_houston, aes(x = median_income, y = blackout)) +\n  geom_boxplot(aes(color = blackout), alpha = 0.8) +\n  labs(title = \"Median Income of Houston Homes based on Blackout Status\",\n       y = \"Blackout Status\",\n       x = \"Median Income\") +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 10 rows containing non-finite values (`stat_boxplot()`).\n```\n:::\n\n::: {.cell-output-display}\n![](texas-blackout_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n### Summarizing statistics \n\ncensus_Y_N_houston %>% \n  group_by(blackout) %>% \n  summarize(mean = mean(median_income, na.rm = TRUE),\n            median = median(median_income, na.rm = TRUE),\n            sd = sd(median_income, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSimple feature collection with 2 features and 4 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 1808144 ymin: 7178529 xmax: 2053896 ymax: 7423349\nProjected CRS: NAD83 / Texas Centric Albers Equal Area\n# A tibble: 2 × 5\n  blackout   mean median     sd                                            Shape\n  <chr>     <dbl>  <dbl>  <dbl>                               <MULTIPOLYGON [m]>\n1 N        67859. 57858. 36526. (((1833927 7192789, 1833903 7193076, 1833766 71…\n2 Y        70939. 59916  39311. (((1895641 7236524, 1896074 7237007, 1896410 72…\n```\n:::\n:::\n\n\n## Discussion\n\nWe found that 778 census tracts had been affected by Texas's 2021 energy crisis, amounting to 164,867 total homes experiencing power outage between the studied dates (Feb 07, 2021 to Feb 16, 2021).\n\nThe average median income for homes that experienced a blackout was \\$70,939, slightly higher than the average median income for homes that didn't experience a blackout, which was \\$67,859. It is important to note that 1) our factor of interest was median income within census tracts and that other socioeconomic factors could reveal unexplored spatial patterns, and that 2) weather conditions were not normalized to conduct this exercise, variable that could cause a different outcome.\n",
    "supporting": [
      "texas-blackout_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}